"""Realistic-format synthetic source documents for the CrimeNet AI dataset pack.

Every document mirrors the layout of the real Indian police / telecom / banking
artefact it represents, and every fact inside it (names, plates, phone numbers,
timestamps, locations) is taken from the application seed data so the paperwork
and the running application always agree.

NOTHING HERE IS REAL. Each file carries a synthetic-data banner.
"""
from __future__ import annotations

from . import ds_source as S

W = 80
RULE = "-" * W
HEAVY = "=" * W


def banner(kind: str) -> str:
    return "\n".join([
        HEAVY,
        "SYNTHETIC DEMONSTRATION DATA - NOT A REAL {}".format(kind.upper()).center(W),
        "Generated for the CrimeNet AI prototype. No real person, vehicle, account,".center(W),
        "case, police station, bank or telecom operator is represented.".center(W),
        "Not evidence. Not for operational, legal or investigative use.".center(W),
        HEAVY,
        "",
    ])


def footer(doc_ref: str, evidence_id: str, case_id: str) -> str:
    return "\n".join([
        "",
        RULE,
        f" Document reference : {doc_ref}",
        f" Ingested into CrimeNet AI as : {evidence_id}   (Case {case_id})",
        f" Classification : {S.CLASSIFICATION}",
        RULE,
    ])


def kv(label: str, value: str, width: int = 34) -> str:
    return f" {label.ljust(width, '.')} : {value}"


# ---------------------------------------------------------------------------
# Standing (document-only) role holders. These are officers, complainants and
# custodians - roles, not network entities - so they deliberately do NOT appear
# in the demo entity graph.
# ---------------------------------------------------------------------------
OFFICIALS = {
    "cc_sho": "Thiru R. Selvaraj, Inspector of Police (PC No. 41207)",
    "cc_si": "Tmt. S. Bhuvaneswari, Sub-Inspector of Police (PC No. 58811)",
    "cc_hc": "Thiru K. Elangovan, Head Constable (HC No. 2214)",
    "tn_sho": "Thiru M. Devanathan, Inspector of Police (PC No. 39004)",
    "cbe_sho": "Thiru P. Sathyamoorthy, Inspector of Police (PC No. 47762)",
    "analyst": "Thiru J. Vetrivel, Inspector (Intelligence Analysis Cell)",
    "telecom_nodal": "Nodal Officer (LEA), Synthetic Telecom Ltd., Chennai Circle",
    "bank_nodal": "Nodal Officer, Bharat Coastal Bank (Synthetic), Chennai Region",
}


# ===========================================================================
# 1. FIRST INFORMATION REPORTS  (Form IF1)
# ===========================================================================
def fir_case_101() -> tuple[str, str]:
    ev = S.EVIDENCE_BY_ID["EV-1024"]
    body = "\n".join([
        banner("First Information Report"),
        "FORM IF1  (INTEGRATED INVESTIGATION FORM - 1)".center(W),
        "FIRST INFORMATION REPORT".center(W),
        "(Under Section 173 of the Bharatiya Nagarik Suraksha Sanhita, 2023".center(W),
        "- erstwhile Section 154 of the Code of Criminal Procedure, 1973)".center(W),
        "",
        RULE,
        " 1. District : Greater Chennai (synthetic)      P.S. : Chennai Central (synthetic)",
        "    Year     : 2025            FIR No. : 0412/2025            Date : 10/08/2025",
        RULE,
        " 2. Act(s) and Section(s)",
        "    (i)   Bharatiya Nyaya Sanhita, 2023 .... Sections 303(2), 317(2) r/w 3(5)",
        "          [erstwhile Indian Penal Code, 1860 - Sections 379, 411 r/w 34]",
        "    (ii)  Other Acts and Sections .......... Motor Vehicles Act, 1988 - s.177",
        RULE,
        " 3. (a) Occurrence of offence : Day  SUNDAY",
        "        Date From 10/08/2025   Date To 10/08/2025",
        "        Time From 09:30 hrs    Time To 09:50 hrs",
        "    (b) Information received at P.S. : Date 10/08/2025    Time 18:20 hrs",
        "    (c) General Diary Reference      : Entry No. 041/2025  Time 18:26 hrs",
        RULE,
        " 4. Type of Information .................. WRITTEN (complaint petition)",
        RULE,
        " 5. Place of Occurrence",
        "    (a) Direction and distance from P.S. : NORTH-EAST, 0.8 km   Beat No. 04",
        "    (b) Address : Public parking apron, Chennai Central approach road,",
        "                  Chennai - 600 003 (synthetic locality reference LOC-001)",
        "    (c) Outside P.S. limits ? ........... NO",
        RULE,
        " 6. Complainant / Informant",
        kv("(a) Name", "Tmt. S. Vasanthi"),
        kv("(b) Husband's Name", "Thiru M. Ganesan"),
        kv("(c) Date / Year of Birth", "1981"),
        kv("(d) Nationality", "Indian"),
        kv("(e) Passport No. / Date / Place", "NIL"),
        kv("(f) Occupation", "Self-employed"),
        kv("(g) Address", "Old No. 14, New No. 27, Wall Tax Road,"),
        " " + " " * 38 + "Chennai - 600 003 (synthetic address)",
        kv("(h) Mobile", "Withheld - available in Case Diary"),
        RULE,
        " 7. Details of known / suspected / unknown accused with full particulars",
        "    (1) Thiru RAVI KUMAR, age approx. 34 years, address not fully ascertained,",
        "        observed in the vicinity of the vehicle at the time of occurrence.",
        "        Status: SUSPECT NOT ESTABLISHED - identity and involvement remain to be",
        "        verified. No arrest effected. No charge framed at the time of registration.",
        "    (2) Other persons, if any - UNKNOWN.",
        RULE,
        " 8. Reasons for delay in reporting by complainant / informant",
        "    Complainant first searched the surrounding parking area and enquired with the",
        "    parking attendant before approaching the Police Station; delay of approx.",
        "    8 hours 30 minutes is explained and accepted.",
        RULE,
        " 9. Particulars of properties stolen / involved",
        "    Sl.  Description                                    Est. Value (INR)",
        "    1.   Motor car bearing registration TN01AB1234,             4,50,000",
        "         make/model withheld, colour white, 2016 model",
        "         Chassis / Engine No. : recorded in Annexure-A",
        RULE,
        "10. Total value of properties stolen / involved ....... INR 4,50,000 (synthetic)",
        RULE,
        "11. Inquest Report / U.D. Case No., if any ............ NOT APPLICABLE",
        RULE,
        "12. F.I.R. CONTENTS",
        "",
        "    The complainant Tmt. S. Vasanthi appeared before this Police Station on",
        "    10/08/2025 at 18:20 hrs and submitted a written complaint stating that her",
        "    motor vehicle bearing registration number TN01AB1234 was parked in the public",
        "    parking apron near Chennai Central on the morning of 10/08/2025 and was found",
        "    missing when she returned at about 12:15 hrs.",
        "",
        "    On preliminary enquiry, the patrol unit (HC 2214) reported that vehicle",
        "    TN01AB1234 was observed near Chennai Central at 09:40 hrs on 10/08/2025 and",
        "    that one Thiru Ravi Kumar was observed near Chennai Central using the said",
        "    vehicle TN01AB1234 at that time. The contact number recorded during the",
        "    complaint proceedings is +919840012345.",
        "",
        "    The patrol unit further reported that the vehicle thereafter moved in the",
        "    direction of Guindy Industrial Estate. The said movement is recorded in the",
        "    patrol note and is yet to be corroborated by independent record.",
        "",
        "    No suspect has been identified or charged as on the date of registration.",
        "    The observation recorded above attributes no offence to any individual and is",
        "    entered solely to preserve the information received.",
        "",
        "    Hence this First Information Report.",
        RULE,
        "13. Action taken : Since the above report reveals commission of offence(s) u/s as",
        "    mentioned at item No. 2, registered the case and took up the investigation.",
        "",
        kv("    Signature of Officer-in-Charge", "/s/ R. Selvaraj"),
        kv("    Name and Rank", OFFICIALS["cc_sho"]),
        kv("    Investigation entrusted to", OFFICIALS["cc_si"]),
        RULE,
        "14. Signature / Thumb impression of the complainant / informant : /s/ S. Vasanthi",
        RULE,
        "15. Date and time of despatch to the Court ........... 11/08/2025, 10:30 hrs",
        RULE,
        "",
        " ANNEXURE-A : Vehicle particulars withheld from this extract.",
        " ANNEXURE-B : Patrol note of HC 2214 dated 10/08/2025 (see surveillance folder).",
        "",
        " NOTE FOR THE CrimeNet AI PIPELINE",
        " The text extracted from this document into evidence item EV-1024 is the",
        " narrative at item 12 above. Extraction is rule-and-NER based; no fact has been",
        " added to the graph that does not appear in this document.",
        footer("FIR No. 0412/2025 - Chennai Central P.S. (synthetic)", "EV-1024", "CASE-101"),
    ])
    return "FIR_0412-2025_CASE-101_Chennai-Central.txt", body


def fir_case_512() -> tuple[str, str]:
    body = "\n".join([
        banner("Community Service Register / Tip Entry"),
        "FORM IF1  (INTEGRATED INVESTIGATION FORM - 1)".center(W),
        "PRELIMINARY INFORMATION ENTRY / ANONYMOUS TIP REGISTER".center(W),
        "(Non-cognizable preliminary entry pending verification)".center(W),
        "",
        RULE,
        " 1. District : Greater Chennai (synthetic)      P.S. : Chennai Central (synthetic)",
        "    Year     : 2025          Register Entry No. : 0731/2025      Date : 01/09/2025",
        RULE,
        " 2. Act(s) and Section(s) ................ NOT ASCERTAINED",
        "    No cognizable offence is disclosed by the information as received.",
        RULE,
        " 3. (a) Occurrence of offence : Day  NOT STATED   Date NOT STATED",
        "        Time From NOT STATED   Time To NOT STATED",
        "    (b) Information received at P.S. : Date 01/09/2025   Time 08:15 hrs",
        "    (c) General Diary Reference      : Entry No. 219/2025  Time 08:19 hrs",
        RULE,
        " 4. Type of Information .................. ORAL (anonymous telephone call)",
        RULE,
        " 5. Place of Occurrence",
        "    (a) Direction and distance from P.S. : NOT STATED BY CALLER",
        "    (b) Address ......................... 'near the market' - NOT SPECIFIC",
        "    (c) Outside P.S. limits ? ........... CANNOT BE DETERMINED",
        RULE,
        " 6. Complainant / Informant .............. ANONYMOUS",
        kv("    Caller identity", "Not disclosed; caller disconnected"),
        kv("    Call-back number", "Not available (number withheld)"),
        RULE,
        " 7. Details of known / suspected / unknown accused ..... NONE PROVIDED",
        "    No name, no description, no vehicle, no phone number was provided.",
        RULE,
        " 8. Reasons for delay in reporting ....... NOT APPLICABLE",
        RULE,
        " 9. Particulars of properties involved ... NONE STATED",
        RULE,
        "10. Total value of properties ............ NIL",
        RULE,
        "12. CONTENTS OF INFORMATION",
        "",
        "    An anonymous caller stated that 'something suspicious is happening near the",
        "    market'. The caller provided no name, no vehicle particulars, no telephone",
        "    number, no specific location, no date or time of the alleged occurrence and",
        "    no supporting record of any kind. The caller disconnected before any",
        "    clarification could be obtained.",
        "",
        "    No prior case reference exists against the information as received.",
        "",
        "    As the information does not disclose the commission of any cognizable",
        "    offence and contains no identifying particular capable of verification, the",
        "    entry is retained in the register pending further information.",
        RULE,
        "13. Action taken : Entered in the register. No investigation taken up for want of",
        "    ascertainable particulars. Beat officer advised to make general enquiry.",
        "",
        kv("    Signature of Officer-in-Charge", "/s/ R. Selvaraj"),
        kv("    Name and Rank", OFFICIALS["cc_sho"]),
        RULE,
        "",
        " NOTE FOR THE CrimeNet AI PIPELINE",
        " This item is included deliberately to exercise the INSUFFICIENT EVIDENCE",
        " pathway. When CASE-512 is analysed the platform must decline to produce a",
        " network, must state INSUFFICIENT EVIDENCE and must name the missing elements",
        " (identity, location, time, corroborating record) rather than infer them.",
        footer("Tip Register Entry No. 0731/2025 (synthetic)", "EV-5120", "CASE-512"),
    ])
    return "FIR_0731-2025_CASE-512_Anonymous-Tip.txt", body


# ===========================================================================
# 2. POLICE REPORTS
# ===========================================================================
def police_report_case_202() -> tuple[str, str]:
    body = "\n".join([
        banner("Police Report"),
        "POLICE REPORT - INVESTIGATION PROGRESS NOTE".center(W),
        "(Case Diary Extract - Part I)".center(W),
        "",
        RULE,
        kv(" Police Station", "Chennai Central (synthetic)"),
        kv(" Crime Number", "Cr. No. 0518/2025"),
        kv(" Sections", "BNS 2023 - ss. 305(a), 317(2) r/w 3(5)"),
        kv(" Internal case reference", "CASE-202  (Coordinated Property Crime)"),
        kv(" Report date and time", "18/08/2025, 10:30 hrs"),
        kv(" Reporting officer", OFFICIALS["cc_si"]),
        kv(" Investigating officer", OFFICIALS["cc_sho"]),
        kv(" Case diary part", "CD No. 03 of 2025 (CASE-202)"),
        RULE,
        "",
        " 1. SUBJECT",
        "    Observations recorded at Chennai Central on the morning of 18/08/2025 in",
        "    connection with reported property offences in the T Nagar and Chennai",
        "    Central corridors.",
        "",
        " 2. OBSERVATIONS RECORDED",
        "",
        "    Sl.  Time    Observation",
        "    " + "-" * 74,
        "    1.   10:05   Vehicle bearing registration TN01AB1234 was observed at",
        "                 Chennai Central. The vehicle was stationary for approximately",
        "                 four minutes on the eastern approach road.",
        "",
        "    2.   10:05   One Thiru R. Kumar was recorded as the person using the said",
        "                 vehicle at that time. Identity was recorded as stated at the",
        "                 spot and has NOT been documentarily verified.",
        "",
        "    3.   10:12   Thiru Arun Selvam was observed at Chennai Central. He was seen",
        "                 in the same public area. No interaction with the occupant of",
        "                 TN01AB1234 was observed or recorded.",
        "",
        "    4.   10:18   Tmt. Meena Raghavan, witness, reported being present at",
        "                 Chennai Central. Her statement is recorded separately under",
        "                 s.180 BNSS (erstwhile s.161 Cr.P.C.).",
        "",
        " 3. ASSESSMENT",
        "    The observations establish presence and vehicle usage at a common location",
        "    within a thirteen-minute window. Presence at a common location does not by",
        "    itself establish a meeting, an association or an offence. No determination",
        "    of involvement has been made against any person named in this report.",
        "",
        " 4. ACTION TAKEN",
        "    (a) Witness statement of Tmt. Meena Raghavan recorded.",
        "    (b) CCTV still from the Chennai Central approach camera secured and",
        "        forwarded to the Intelligence Analysis Cell (see image folder).",
        "    (c) Requisition issued to the Regional Transport Office for the registered",
        "        ownership particulars of TN01AB1234. Reply awaited.",
        "",
        " 5. FURTHER ACTION PROPOSED",
        "    (a) Obtain authorised vehicle ownership record for TN01AB1234.",
        "    (b) Obtain documentary identity proof for the person recorded as R. Kumar.",
        "    (c) Verify whether the person recorded as R. Kumar in this case and the",
        "        person recorded as Ravi Kumar in CASE-101 are the same individual.",
        "        Until such verification, the two records are to be treated as SEPARATE.",
        "",
        kv(" Signature of reporting officer", "/s/ S. Bhuvaneswari"),
        kv(" Countersigned", "/s/ R. Selvaraj, Inspector of Police"),
        footer("Cr. No. 0518/2025, CD-03 (synthetic)", "EV-2041", "CASE-202"),
    ])
    return "POLICE-REPORT_Cr-0518-2025_CASE-202_Chennai-Central.txt", body


def police_report_case_407() -> tuple[str, str]:
    body = "\n".join([
        banner("Police Report"),
        "POLICE REPORT - COMPLAINT ENQUIRY NOTE".center(W),
        "(Document irregularity enquiry - preliminary)".center(W),
        "",
        RULE,
        kv(" Police Station", "R S Puram, Coimbatore City (synthetic)"),
        kv(" Enquiry Number", "Enq. No. 0134/2025"),
        kv(" Sections (proposed)", "BNS 2023 - ss. 336(3), 340(2) [under scrutiny]"),
        kv(" Internal case reference", "CASE-407 (Coimbatore Transport Document Inquiry)"),
        kv(" Report date and time", "26/08/2025, 11:00 hrs"),
        kv(" Reporting officer", OFFICIALS["cbe_sho"]),
        RULE,
        "",
        " 1. SUBJECT",
        "    Complaint of documentation irregularities in transport consignment papers",
        "    reported by a logistics operator at Coimbatore R S Puram.",
        "",
        " 2. PARTICULARS",
        "",
        "    Sl.  Date        Particular",
        "    " + "-" * 74,
        "    1.   26/08/2025  Thiru Prakash Menon reported documentation irregularities",
        "                     involving vehicle TN22CD3311 at Coimbatore R S Puram.",
        "",
        "    2.   26/08/2025  Tmt. Anitha Rao, transport clerk, provided a statement",
        "                     regarding the preparation of the consignment documents.",
        "",
        "    3.   27/08/2025  Thiru Sanjay Prabhu is named in a transport document",
        "                     dated 27/08/2025 produced during the enquiry.",
        "",
        " 3. ASSESSMENT",
        "    The matter is at the enquiry stage. No link to the Chennai cases has been",
        "    established from this record alone. Any apparent similarity of modus or of",
        "    entity names must not be treated as a connection in the absence of a shared",
        "    identifier supported by evidence.",
        "",
        " 4. ACTION TAKEN",
        "    Statements recorded. Original consignment documents retained under receipt.",
        "    Copies forwarded to the Intelligence Analysis Cell for record comparison.",
        "",
        kv(" Signature of reporting officer", "/s/ P. Sathyamoorthy"),
        footer("Enq. No. 0134/2025 (synthetic)", "EV-4090", "CASE-407"),
    ])
    return "POLICE-REPORT_Enq-0134-2025_CASE-407_Coimbatore.txt", body


# ===========================================================================
# 3. SURVEILLANCE REPORT
# ===========================================================================
def surveillance_report_case_101() -> tuple[str, str]:
    body = "\n".join([
        banner("Surveillance Report"),
        "FIELD OBSERVATION LOG - SURVEILLANCE REPORT".center(W),
        "(Static observation, public place, no intrusive method employed)".center(W),
        "",
        RULE,
        kv(" Operation reference", "OP-KAVAL/CASE-101/07 (synthetic)"),
        kv(" Authority", "Written authority of the Deputy Commissioner"),
        " " + " " * 36 + "  (Ref. DC/CCB/AUTH/2025/119, dated 11/08/2025)",
        kv(" Observation post", "Public footway, Guindy Industrial Estate"),
        kv(" Date", "12/08/2025"),
        kv(" Duration of observation", "11:45 hrs to 13:10 hrs"),
        kv(" Observation team", "HC 2214 (K. Elangovan), PC 6690 (T. Anbarasu)"),
        kv(" Method", "Visual observation from public place only"),
        kv(" Recording device", "Departmental camera DC-114 (still images only)"),
        kv(" Internal case reference", "CASE-101"),
        RULE,
        "",
        " 1. OBSERVATION LOG",
        "",
        "    Time   Obs.  Entry",
        "    " + "-" * 74,
        "    11:45  001   Observation commenced. Location: open compound adjoining Unit",
        "                 14, Guindy Industrial Estate. Light: clear. Visibility: good.",
        "",
        "    12:30  002   Vehicle bearing registration TN07XY4455 was observed parked at",
        "                 Guindy Industrial Estate, facing north, engine off.",
        "                 Still image ref: DC-114/2025/0812/0007.",
        "",
        "    12:31  003   Two male persons were observed near the vehicle. They were",
        "                 subsequently identified from departmental records as Thiru",
        "                 Karthik Rajan and Thiru Mohan Das. Identification is by",
        "                 photograph comparison only and is NOT documentarily confirmed.",
        "",
        "    12:35  004   Thiru Ravi Kumar was reported present in the same area at",
        "                 12:35 hrs according to the patrol note of the beat officer.",
        "                 This entry is a second-hand report and was not directly",
        "                 observed by this team.",
        "",
        "    12:52  005   The two persons at entry 003 left the compound on foot in a",
        "                 westerly direction. Vehicle TN07XY4455 remained parked.",
        "",
        "    13:10  006   Observation concluded. No approach, no stop and no interaction",
        "                 with any person was made by the observation team.",
        "",
        " 2. ASSESSMENT",
        "    The log records presence and proximity only. Proximity between persons and a",
        "    vehicle in a public place does not establish possession, use, association or",
        "    the commission of any offence. Entry 004 is uncorroborated hearsay within",
        "    this document and requires independent support before any reliance.",
        "",
        " 3. CAVEAT",
        "    This report is descriptive only and attributes no offence to any individual.",
        "    No intrusive technique, no interception and no entry upon private premises",
        "    was employed or authorised.",
        "",
        kv(" Signature", "/s/ K. Elangovan, HC 2214"),
        kv(" Countersigned", "/s/ R. Selvaraj, Inspector of Police"),
        footer("OP-KAVAL/CASE-101/07 (synthetic)", "EV-1026", "CASE-101"),
    ])
    return "SURVEILLANCE-REPORT_OP-KAVAL-07_CASE-101_Guindy.txt", body


# ===========================================================================
# 4. INTELLIGENCE REPORTS  (5x5x5 grading)
# ===========================================================================
def _int_header(ref: str, date: str, originator: str, grading: tuple[str, str, str]) -> list[str]:
    src, intel, handling = grading
    return [
        RULE,
        kv(" Report reference", ref),
        kv(" Date of report", date),
        kv(" Originating unit", originator),
        kv(" Dissemination", "Restricted - investigating officers of the named case"),
        RULE,
        " 5x5x5 INFORMATION / INTELLIGENCE EVALUATION",
        f"   Source evaluation ....... {src}",
        f"   Intelligence evaluation . {intel}",
        f"   Handling code ........... {handling}",
        RULE,
    ]


def intel_report_case_202() -> tuple[str, str]:
    body = "\n".join([
        banner("Intelligence Report"),
        "INTELLIGENCE REPORT (5x5x5)".center(W),
        "UNVERIFIED - NOT EVIDENCE".center(W),
        "",
        *_int_header(
            "INT/CCB/2025/0442", "19/08/2025", "Intelligence Analysis Cell (synthetic)",
            ("D - Untested source",
             "4 - Cannot be judged; no means of assessing the information",
             "2 - Dissemination permitted to other agencies, no onward release"),
        ),
        "",
        kv(" Related case reference", "CASE-202"),
        kv(" Related evidence in system", "EV-2043"),
        "",
        " 1. INFORMATION RECEIVED",
        "",
        "    An unverified note states that Thiru Ravi Kumar was reported at Madurai on",
        "    18/08/2025 at 10:00 hrs.",
        "",
        "    This directly conflicts with the Chennai Central observation recorded in",
        "    the police report at Cr. No. 0518/2025 (system reference EV-2041), which",
        "    places the same identity profile at Chennai Central at 10:05 hrs on the",
        "    same date. The two locations are approximately 460 km apart; the reported",
        "    positions are not physically reconcilable within a five-minute interval.",
        "",
        "    The note further states that Thiru Vignesh Anand is named in connection",
        "    with vehicle TN09KL8899 at T Nagar on 19/08/2025.",
        "",
        " 2. HANDLING DIRECTION - CONTRADICTION",
        "",
        "    This contradiction is retained DELIBERATELY and must NOT be suppressed,",
        "    reconciled or averaged during analysis. Either",
        "      (a) one of the two reports is inaccurate, or",
        "      (b) the two records refer to two different individuals bearing similar",
        "          names.",
        "    Until the point is resolved by documentary identity evidence, the identity",
        "    hypothesis Ravi Kumar <-> R. Kumar must be held as NOT ESTABLISHED.",
        "",
        " 3. RELIABILITY CAVEAT",
        "    The source has not previously provided information to this unit. The",
        "    information is uncorroborated and carries no evidentiary weight. It may not",
        "    be used as the basis of any coercive action.",
        "",
        kv(" Prepared by", OFFICIALS["analyst"]),
        footer("INT/CCB/2025/0442 (synthetic)", "EV-2043", "CASE-202"),
    ])
    return "INTELLIGENCE-REPORT_INT-2025-0442_CASE-202.txt", body


def intel_report_case_305() -> tuple[str, str]:
    body = "\n".join([
        banner("Intelligence Report"),
        "INTELLIGENCE REPORT (5x5x5)".center(W),
        "UNVERIFIED - NOT EVIDENCE".center(W),
        "",
        *_int_header(
            "INT/IAC/2025/0517", "25/08/2025", "Intelligence Analysis Cell (synthetic)",
            ("C - Source of limited reliability",
             "3 - Information not known personally to the source but corroborated",
             "2 - Dissemination permitted to other agencies, no onward release"),
        ),
        "",
        kv(" Related case reference", "CASE-305"),
        kv(" Related evidence in system", "EV-3071"),
        "",
        " 1. INFORMATION RECEIVED",
        "",
        "    Thiru Ravi K. was reported near Chennai Port on 25/08/2025 in the company",
        "    of a vehicle recorded as TN01AB1234.",
        "",
        "    Thiru Arun Selvam was observed at Chennai Port at 15:20 hrs on 25/08/2025.",
        "",
        "    Coastal Logistics Pvt Ltd operates a facility in the same area.",
        "",
        " 2. ANALYTICAL OBSERVATION",
        "",
        "    Vehicle TN01AB1234 now appears in three separate case files (CASE-101,",
        "    CASE-202 and CASE-305). The registration number is a strong identifier and",
        "    is the only element common to all three files that is supported by a",
        "    documentary record in each.",
        "",
        "    The name variants 'Ravi Kumar', 'R. Kumar' and 'Ravi K.' are NOT to be",
        "    treated as the same person on the strength of name similarity alone.",
        "",
        " 3. RELIABILITY CAVEAT",
        "    The note is unverified and carries no evidentiary weight without",
        "    corroboration from an authorised record.",
        "",
        kv(" Prepared by", OFFICIALS["analyst"]),
        footer("INT/IAC/2025/0517 (synthetic)", "EV-3071", "CASE-305"),
    ])
    return "INTELLIGENCE-REPORT_INT-2025-0517_CASE-305.txt", body


# ===========================================================================
# 5. LEGAL PAPERWORK - requisitions and electronic-record certificates
# ===========================================================================
def cdr_requisition() -> tuple[str, str]:
    body = "\n".join([
        banner("Requisition Letter"),
        "OFFICE OF THE INSPECTOR OF POLICE".center(W),
        "CHENNAI CENTRAL POLICE STATION (SYNTHETIC)".center(W),
        "",
        kv(" Reference", "Cr. No. 0412/2025 / CDR / 03"),
        kv(" Date", "12/08/2025"),
        "",
        " To",
        "    " + OFFICIALS["telecom_nodal"],
        "",
        " Sir / Madam,",
        "",
        " Sub: Requisition for Call Detail Records - Cr. No. 0412/2025 u/s 303(2) BNS -",
        "      reg.",
        " Ref: Section 94 of the Bharatiya Nagarik Suraksha Sanhita, 2023",
        "      (erstwhile Section 91 of the Code of Criminal Procedure, 1973)",
        "",
        "    In connection with the investigation of the case cited above, you are",
        " required to furnish the Call Detail Records, subscriber details and cell site",
        " particulars in respect of the following mobile numbers for the period from",
        " 10/08/2025 00:00 hrs to 19/08/2025 23:59 hrs:",
        "",
        "      1. +91 98400 12345",
        "      2. +91 98400 99887",
        "",
        "    The records may be furnished in machine-readable form together with the",
        " certificate under Section 63(4)(c) of the Bharatiya Sakshya Adhiniyam, 2023",
        " (erstwhile Section 65B of the Indian Evidence Act, 1872).",
        "",
        "    No content of communication is sought. Only metadata as maintained in the",
        " ordinary course of business is required.",
        "",
        "                                                    Yours faithfully,",
        "",
        "                                                    /s/ R. Selvaraj",
        "                                                    " + OFFICIALS["cc_sho"],
        footer("Cr. No. 0412/2025 / CDR / 03 (synthetic)", "EV-1025", "CASE-101"),
    ])
    return "CDR-REQUISITION_Cr-0412-2025_CASE-101.txt", body


def certificate_63(subject: str, ref: str, evidence_id: str, case_id: str,
                   custodian: str, device: str, produced_on: str, sha: str = "") -> tuple[str, str]:
    body = "\n".join([
        banner("Certificate"),
        "CERTIFICATE UNDER SECTION 63(4)(c)".center(W),
        "OF THE BHARATIYA SAKSHYA ADHINIYAM, 2023".center(W),
        "(erstwhile Section 65B of the Indian Evidence Act, 1872)".center(W),
        "",
        RULE,
        kv(" Certificate reference", ref),
        kv(" Subject of the certificate", subject),
        kv(" Related case", case_id),
        kv(" System evidence reference", evidence_id),
        kv(" Date of production", produced_on),
        RULE,
        "",
        " I, the undersigned, being the person occupying a responsible official position",
        " in relation to the operation of the computer system described below, do hereby",
        " certify that:",
        "",
        " 1. The electronic record produced is a copy of information contained in a",
        "    computer output produced by the following system in the ordinary course of",
        "    its activities:",
        f"       {device}",
        "",
        " 2. Throughout the material period the said computer was operating properly, or",
        "    if not, any respect in which it was not operating properly was not such as",
        "    to affect the electronic record or the accuracy of its contents.",
        "",
        " 3. The information contained in the electronic record reproduces or is derived",
        "    from information supplied to the computer in the ordinary course of the said",
        "    activities.",
        "",
        " 4. The hash value of the produced electronic record is recorded below and may",
        "    be used to verify that the record has not been altered after production:",
        f"       SHA-256 : {sha or '<computed at export time - see DATASET_MANIFEST.csv>'}",
        "",
        kv(" Name and designation", custodian),
        kv(" Signature", "/s/ (synthetic)"),
        "",
        " NOTE: This is a SYNTHETIC specimen certificate created to demonstrate the",
        " chain-of-custody and hash-verification workflow of the CrimeNet AI prototype.",
        " It has no legal effect whatsoever.",
        footer(ref, evidence_id, case_id),
    ])
    slug = ref.replace("/", "-").replace(" ", "")
    return f"CERTIFICATE-63-BSA_{slug}_{evidence_id}.txt", body


def bank_requisition() -> tuple[str, str]:
    body = "\n".join([
        banner("Requisition Letter"),
        "OFFICE OF THE INSPECTOR OF POLICE".center(W),
        "INTELLIGENCE ANALYSIS CELL (SYNTHETIC)".center(W),
        "",
        kv(" Reference", "CASE-305 / BANK / 01"),
        kv(" Date", "22/08/2025"),
        "",
        " To",
        "    " + OFFICIALS["bank_nodal"],
        "",
        " Sir / Madam,",
        "",
        " Sub: Requisition for account statement and KYC particulars - CASE-305 - reg.",
        " Ref: Section 94 of the Bharatiya Nagarik Suraksha Sanhita, 2023",
        "",
        "    You are required to furnish certified statements of account and the KYC",
        " particulars in respect of the following accounts for the period 18/08/2025 to",
        " 25/08/2025:",
        "",
        "      1. A/C 33901122",
        "      2. A/C 44120987",
        "",
        "    The statements may be furnished in machine-readable form together with the",
        " certificate under Section 63(4)(c) of the Bharatiya Sakshya Adhiniyam, 2023.",
        "",
        "                                                    Yours faithfully,",
        "",
        "                                                    /s/ J. Vetrivel",
        "                                                    " + OFFICIALS["analyst"],
        footer("CASE-305 / BANK / 01 (synthetic)", "EV-3070", "CASE-305"),
    ])
    return "BANK-REQUISITION_CASE-305.txt", body


def chain_of_custody(evidence_id: str) -> tuple[str, str]:
    ev = S.EVIDENCE_BY_ID[evidence_id]
    case_id = ev["case_id"]
    rows = [
        ("1", ev["timestamp"][:10], "Seized / received at Police Station",
         "Station House Officer", "Original retained in Malkhana"),
        ("2", ev["timestamp"][:10], "Copy produced for analysis",
         ev["uploaded_by"], "Working copy created; original untouched"),
        ("3", ev["timestamp"][:10], "Registered in CrimeNet AI",
         ev["uploaded_by"], "SHA-256 computed at registration and sealed in ledger"),
    ]
    if evidence_id == "EV-2042":
        rows.append(("4", "2025-08-19", "Stored object modified OUTSIDE the application",
                     "UNKNOWN", "DELIBERATE DEMONSTRATION - integrity check will report "
                                "INTEGRITY MISMATCH against the registered hash"))
    lines = [
        banner("Chain of Custody Form"),
        "CHAIN OF CUSTODY / EVIDENCE MOVEMENT REGISTER".center(W),
        "",
        RULE,
        kv(" System evidence reference", evidence_id),
        kv(" Case", f"{case_id} - {S.CASE_BY_ID[case_id]['title']}"),
        kv(" Evidence type", ev["evidence_type"]),
        kv(" Source", ev["source"]),
        kv(" Recorded timestamp", ev["timestamp"]),
        kv(" Registered by", ev["uploaded_by"]),
        kv(" Verification status in system", ev.get("verification_status", "UNVERIFIED")),
        RULE,
        "",
        " Sl.  Date         Movement / Action                Custodian        Remarks",
        " " + "-" * 78,
    ]
    for sl, date, action, cust, remark in rows:
        lines.append(f" {sl:<4} {date:<12} {action:<32} {cust:<16}")
        lines.append(f"      Remarks: {remark}")
    lines += [
        "",
        " DECLARATION",
        " The original record has not been modified by the CrimeNet AI platform. The",
        " platform stores an immutable copy, records its SHA-256 digest at the moment of",
        " registration and seals that digest in an append-only hash-chained ledger.",
        footer(f"COC/{evidence_id} (synthetic)", evidence_id, case_id),
    ]
    return f"CHAIN-OF-CUSTODY_{evidence_id}.txt", "\n".join(lines)
